### Variables
@baseUrl = http://localhost:3000/api

### AUTH ROUTES
### 1. REGISTRAR UN NUEVO USUARIO - POST
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Mario garcia bernal",
    "email": "mrgbplay3@gmail.com",
    "password": "clave345"
}

### 2. REGISTRAR OTRO USUARIO - POST
POST {{baseUrl}}/auth/register
Content-Type: application/json



### 3. OBTENER TODOS LOS USUARIOS - GET
GET {{baseUrl}}/auth/users
Content-Type: application/json

### 4. OBTENER USUARIO POR ID - GET (Cambiar el ID con uno real)
GET {{baseUrl}}/auth/users/6992f2617f3a553c75abcaf4
Content-Type: application/json

### 5. ELIMINAR USUARIO - DELETE (Cambiar el ID con uno real)
DELETE {{baseUrl}}/auth/users/6992f2617f3a553c75abcaf4
Content-Type: application/json